[app]
    logger_enabled = false
    verbose = false

[resources]
    [resources.data]
    path_dir = "$PROJECT_MODULES/data"
    # path_dir = "$CONFIG_DIR/data"

    [resources.assigns]
    path_dir = "$PROJECT_MODULES/data/assigns"
